dataset: 'highbay'
sync_method: strict # loose
coarse: True
verbose: False
meshing:
  resolution: 256
tracking:
  vis_freq: 50 #50
  vis_inside_freq: 25 #25
  ignore_edge_W: 0
  ignore_edge_H: 0
  seperate_LR: True
  const_speed_assumption: True
  lr: 0.0005     # 0.0005 
  pixels: 1000 # 2000
  iters: 30 # 100
  use_color_in_tracking: True
  w_color_loss: 0.5 #0.5
  handle_dynamic: True
  car_model: True
# 新增
rendering:
  N_samples: 64 # 32
  N_surface: 32 # 16

mapping:
  keyframe_selection_method: 'overlap'
  ignore_edge_W: 0
  ignore_edge_H: 20
  every_frame: 5
  vis_freq: 50 #50
  vis_inside_freq: 30 #25
  mesh_freq: 50
  ckpt_freq: 500
  keyframe_every: 20 #50
  mapping_window_size: 10 #10
  pixels: 2000
  iters_first: 500
  iters: 50 #10
  middle_iter_ratio: 0.4
  fine_iter_ratio: 0.6
  decay_scale: 0.1
  decay_threshold: 0.61
  decay_second_threshold: 0.37
  iters_first: 1500
  # # for scene 1
  # marching_cubes_bound: [[-5.0,5.0],[-3.0,5.0],[0.0,20.0]]
  # bound: [[-5.0,5.0],[-3.0,5.0],[0.0,20.0]]
  # for scene 2
  marching_cubes_bound: [[-5.0,5.0],[-3.0,5.0],[0.0,20.0]]
  bound: [[-5.0,15.0],[-3.0,5.0],[0.0,25.0]]

cam: 
  H: 720 
  W: 1280
  fx: 526.9379272460938
  fy: 526.9379272460938
  cx: 616.2449951171875
  cy: 359.21929931640625
  png_depth_scale: 1000.0 #for depth image in png format 1000
  crop_edge: 10 # 10
data:
  input_folder: Datasets/ParkFusion
  output: output/parkingDemo
Depthmodel:
  path: src/deeppruner_simplify/model/kiti_testfinetune_119.tar
  depth_fusion_scale: 10